# Config file for automatic testing at travis-ci.org
os: linux
dist: xenial
jobs:
  include:
    - language: python
      python:
        - 2.7
      install:
        - pip install cookiecutter
      script:
        - cookiecutter . --no-input
    - language: python
      python:
        - 3.5
      install:
        - pip install cookiecutter
      script:
        - cookiecutter . --no-input
    - language: java
      install:
        - pip install cookiecutter
      script:
        - cookiecutter . --no-input
        - chmod +x ./kotlin-scaffold/gradlew
        - cd ./kotlin-scaffold
        - ./gradlew check
        - ./gradlew jacocoTestReport
      after_success:
        - bash <(curl -s https://codecov.io/bash) -d -k kotlin-scaffold
