# Config file for automatic testing at travis-ci.org
language: python
python:
  - 2.7
  - 3.5
install:
  - pip install cookiecutter
script:
  - cookiecutter . --no-input
  - chmod +x ./kotlin-scaffold/gradlew
  - ./kotlin-scaffold/gradlew check
  - ./kotlin-scaffold/gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
